ProyectoFinal/BlogApp/urls.py
from django.urls import path
from .views import *
from Users.views import messages, new_message

app_name = 'blogapp'

urlpatterns = [
    path("", home, name='Home'),
    path('posts/', posts, name='Posts'),
    path('posts/list/', PostList.as_view(), name='PostsList'),
    path('post/<pk>', PostDetail.as_view(), name='PostDetail'),
    path('post/delete/<pk>', PostDelete.as_view(), name='PostDelete'),
    path('post_form/', postForm, name='PostForm'),
    path('post/edit/<post_id>/', editPost, name='EditPost'),
    
    path('search_post/', searchPost, name="SearchPost"),
    path('search_result/', searchResult, name="SearchResult"),

    path('about/', about, name="About"),

    path('inbox/', messages, name='Messages'),
    path('inbox/new_msg/', new_message, name='NewMessage'),
]

ProyectoFinal/Users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', login_request, name='Login'),
    path('register/', register, name='Register'),
    path('logout/', LogoutView.as_view(template_name='Users/logout.html'), name='Logout'),   #el logout tiene su propia View y dentro del parentesis configuramos la vista
    path('editProfile/', editProfile, name='editProfile'),
    path('profile/<user_id>', profile, name='Profile'),
    path('edit/avatar/', editAvatar, name='editAvatar'),
]

ProyectoFinal/projectBlog/urls.py
from django.contrib import admin
from django.urls import path, include
#Para las imagenes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BlogApp.urls')),
    path('Users/', include('Users.urls')),
]

#Para las imagenes
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/Users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Avatar(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)   #vinvulo con el usuario
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)  #Subcaperta avatars de media

    def __str__(self):
        return f"Imagen perfil del user: {self.user}"


class Messages(models.Model):
    
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver")
    msg = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)    
    
    def __str__(self):
        return f"{self.msg[:50]}[...]"

ProyectoFinal/Users/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):

    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2'] 
        #Saca los mensajes de ayuda
        help_texts = {k:"" for k in fields}


class UserEditForm(UserCreationForm):
    username = forms.CharField(label='Username')
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label='Nombre', required=False)
    last_name = forms.CharField(label='Apellido', required=False) 
    password1 = forms.CharField(label='New Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','first_name','last_name','password1', 'password2']
        help_texts = {k:"" for k in fields}



class AvatarForm(forms.ModelForm):

    class Meta:
        model = Avatar
        fields = ['avatar']


class MessageForm(forms.ModelForm):
    
    class Meta:
        model = Messages
        fields = ['receiver','msg',]
        widgets = {'msg': forms.Textarea(attrs={'cols': 80})}  # widget para agrandar el TextField a 80 columnas

ProyectoFinal/Users/views.py
from django.shortcuts import render, redirect
from django.urls.base import reverse

from .models import *
from .forms import *

#para el login:
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
#mixin y decoradores:
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, user_passes_test

#for complex lookups (AND/OR)
from django.db.models import Q

# Create your views here.

#---------------login-------------------------------------------------------

def login_request(request):

      if request.method == "POST":
            form = AuthenticationForm(request=request, data = request.POST)

            if form.is_valid():
                  usuario = form.cleaned_data.get('username')   #este usuario es el que ingresa por teclado la persona, idem la clave de abajo
                  contra = form.cleaned_data.get('password')

                  user = authenticate(username=usuario, password=contra)   #este user es el que está en mi BD, si existe seguiria abajo

                  if user is not None:         #si el usario ingresado no es None (quiere decir que existe), listo, pedir que se loguee
                        login(request, user)
                        return render(request,"BlogApp/home.html",  {"mensaje":f"Bienvenido al blog, {usuario}"})   #si es correcto, loguea y me responde welcome
                  else:
                        return render(request,"Users/login.html", {"form":form, "mensaje":"Error, el username es incorrecto. Intentelo nuevamente."})   #y si el usuario que ingresó no corresponde a nadie en la BD, me pasa que es incorrecto

            else:
                        return render(request,"Users/login.html" ,  {"form":form, "mensaje":"Error, la informacion es incorrecta. Intentelo nuevamente."})  #esto se hace si no se cumple la condicion de que el formulario sea valido

      form = AuthenticationForm()    #si no viene por POST, tenemos que mostrar un formulario vacio para que se ingrese
      return render(request,"Users/login.html", {'form':form})

# y despues creamos el Logout directamente en urls.py


#--------------------registrar nuevo usuario----------------------------
#para esto creamos un nuevo form

def register(request):

      if request.method == 'POST':
            form = UserRegisterForm(data=request.POST)
            if form.is_valid():
                  new_user = form.save()
                  login(request, new_user)
                  return redirect(reverse('users:Profile', args=[id]))
            else:
                return render(request, 'Users/register.html', {"form":form, "mensaje": "El user no pudo ser creado. Intentelo nuevamente."})
      
      else:      
            form = UserRegisterForm()     
      return render(request, 'Users/register.html',  {"form":form})


#---------------------editarPerfil---------------------------------------
#para esto creamos un nuevo form

@login_required
def editProfile(request):

      user = request.user
      #buscamos si el usuario tiene avatar:
      try:
          avatar = Avatar.objects.get(user=request.user.id)
          avatar = avatar.avatar.url
      except:
          avatar = ''
     
      if request.method == 'POST':
            myForm = UserEditForm(request.POST, instance=user) 
            if myForm.is_valid():

                  info = myForm.cleaned_data
                  #Datos que se modificarán
                  user.username = info['username']
                  user.email = info['email']
                  user.first_name = info['first_name']
                  user.last_name = info['last_name']
                  user.password1 = info['password1']
                  user.password2 = info['password1']
                  user.save()

                  return redirect(reverse('users:Profile', args=[id]))
            else:
                return render(request, 'Users/edit_profile.html', {"myform":myForm, "mensaje": "El user no pudo ser actualizado. Intentelo nuevamente."})

      else: 
            myForm= UserEditForm(initial={'username':user.username, 'email':user.email, 'first_name':user.first_name, 'last_name':user.last_name}) #Creo el formulario con los datos que voy a modificar
      return render(request, 'Users/edit_profile.html', {"myForm":myForm, "user":user})  #Voy al html que me permite editar


#-----------------------Ver/Editar el perfil de user---------------------------------

@login_required
def profile(request, user_id):
    
    user = request.user
    # buscamos si el usuario tiene avatar:
    try:
        avatar = Avatar.objects.get(user=request.user.id)
        avatar = avatar.avatar.url
    except:
        avatar = ''

    context = {'user': user, 'avatar': avatar, 'title': 'Profile'}
    return render(request, 'Users/profile.html', context)


@user_passes_test(lambda u: u.is_superuser)   # solo los superusers pueden cambiar el avatar
def editAvatar(request):
    
    user = request.user
    # buscamos si el usuario tiene avatar:
    try:
        avatar = Avatar.objects.get(user=request.user.id)
        avatar = avatar.avatar.url
    except:
        avatar = ''

    if request.method == 'POST':
        form_avatar= AvatarForm(request.POST, request.FILES, instance=user)
        if form_avatar.is_valid():
            u = User.objects.get(username=request.user)
            new_avatar = Avatar(user=u, avatar=form_avatar.cleaned_data['avatar'])
            new_avatar.save()
            return redirect(reverse('users:Profile', args=[id]))
        else:
            return render(request, 'Users/edit_avatar.html', {"form_avatar":form_avatar, "mensaje": "El avatar no pudo ser actualizado. Intentelo nuevamente."})
    else:
        form_avatar= AvatarForm()
    return render (request, 'Users/edit_avatar.html', {"form_avatar":form_avatar, "avatar":avatar})


#--------------------------Messages (Inbox and send new msg)--------------------------------------------

@login_required
def messages(request):
    
    user = request.user
    # buscamos si el usuario tiene avatar:
    try:
        avatar = Avatar.objects.get(user=request.user.id)
        avatar = avatar.avatar.url
    except:
        avatar = ''
    
    messages = Messages.objects.filter(Q(receiver=user) | Q(sender=user)).order_by('-sent_at')
    received = messages.filter(receiver=user).order_by('-sent_at')
    sent = messages.filter(sender=user).order_by('-sent_at')

    context = {'title': 'Inbox', 'user': user, 'messages': messages, 'received': received, 'sent':sent, 'avatar': avatar}
    return render(request, 'Users/messages.html', context)


@login_required
def new_message(request):
    
    user = request.user
    # buscamos si el usuario tiene avatar:
    try:
        avatar = Avatar.objects.get(user=request.user.id)
        avatar = avatar.avatar.url
    except:
        avatar = ''

    if request.method != 'POST':
        form = MessageForm()
    else:
        # Data submitted > form con datos ingresados por POST
        form = MessageForm(data=request.POST)
        if form.is_valid():

            msg = form.save(commit=False)
            msg.sender = request.user
            msg.save()
            return redirect ('blogapp:Messages')
    
    context = {'form': form,'title': 'New message','avatar':avatar}
    return render(request, 'Users/new_msg.html', context)

ProyectoFinal/Users/templates/Users/edit_avatar.html
{% extends 'Users/profile.html' %}

{% block messages %}

<!-- Formulario para cargar imagen  -->


<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form_avatar.as_p }}
    <input type="submit" value="Save" class="w3-button w3-round-large w3-button w3-large w3-indigo w3-margin-bottom">
</form>

<a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo w3-margin-top" href=" {% url 'users:editProfile' %} ">Return</button></a>

{% endblock messages %}

ProyectoFinal/Users/templates/Users/edit_profile.html
{% extends 'BlogApp/template.html' %}

{% block content %}

<div class="w3-panel w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    <h1>Actualizando el perfil de {{user}}</h1>
</div>

<!-- Modificar/Agregar avatar -->
{% if user.is_superuser %}
<div div class="w3-container w3-card-4">
    <p>Click aqui para actualizar el Avatar <a class="w3-button w3-black w3-border" href="{% url 'users:editAvatar' %}"><i class="fa fa-file-image-o"></i></a></p>
</div>
{% else %}
<div class="w3-panel w3-blue-gray">
    <h5>No esta autorizado a cambiar su Avatar</h5>
</div>
{% endif %}

<!-- Username to display -->
<div class="w3-card w3-dark-grey w3-round-xlarge">
    <h2 class="w3-center"><b>{{user.username}}</b></h2>
</div>


<!-- Formulario data usuario -->
<div>
    <h3>{{mensaje}}</h3>
    <form action="{% url 'users:editProfile' %}" method="post">{% csrf_token %}
        
        <table class="w3-table w3-topbar w3-bottombar w3-border-dark-grey w3-round">
            {{ myForm.as_table }}
        </table>
        
        <!-- Botones -->
        <div class="w3-bar w3-padding-32">
            <input button type="submit" class="w3-button w3-round-large w3-button w3-large w3-indigo" value="Save changes">
            <a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo" href=" {% url 'users:Profile' user.id %} ">Cancel</button></a>
        </div>
    </form>
</div>


{% endblock %}

ProyectoFinal/Users/templates/Users/login.html
{% extends 'BlogApp/template.html' %}

{% block content %}
   
<!-- Formulario -->
<h3>Iniciar sesion:</h3>
<form action="{% url 'users:Login' %}" method="POST">{% csrf_token %}
    <table class="w3-table w3-topbar w3-bottombar w3-border-dark-grey w3-round">
        {{ form.as_table }}
    </table>
        
        <!-- Botones -->
    <div class="w3-bar w3-padding-32">
        <input button type="submit" class="w3-button w3-round-large w3-button w3-large w3-indigo" value="Iniciar Sesión">
        <a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo" href=" {% url 'blogapp:Home' %} ">Inicio</button></a>
    </div>
</form>

{% endblock %}

ProyectoFinal/Users/templates/Users/logout.html
{% extends 'BlogApp/template.html' %}

{% block content %}

<div class="w3-panel w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    <h1 style="color: black" class="w3-center">Ha cerrado exitosamente su sesion.</h1>
</div>

{% endblock %}

ProyectoFinal/Users/templates/Users/messages.html
{% extends 'Users/profile.html' %}

{% block messages %}

<div class="w3-panel w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    <h1>{{title}}</h1>
</div>

<!-- Inbox table -->

<!-- Received messages -->
<div class="w3-container w3-padding-16">
    <p class="w3-monospace w3-dark-grey">Inbox</p>
    <table class="w3-table-all w3-card-4">
        <thead>
            <tr class="w3-wide">
                <th>From:</th>
                <th>Content</th>
                <th>Received</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for msg in received %}
                <tr>
                    <th>{{msg.sender}}</th>
        
                    <td>{{msg.msg}}
                    <td>{{msg.sent_at}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>    

<!-- Sent messages -->
<div class="w3-container w3-padding-16">
    <p class="w3-monospace w3-dark-grey">Sent</p>
    <table class="w3-table-all w3-card-4">
        <thead>
            <tr class="w3-wide">
                <th>To:</th>
                <th>Content</th>
                <th>Sent</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for msg in sent %}
                <tr>
                    <th>{{msg.receiver}}</th>
        
                    <td>{{msg.msg}}
                    <td>{{msg.sent_at}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>    

<!-- Buttons -->
<div class="w3-bar w3-padding-32 w3-center">
    <a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo" href=" {% url 'blogapp:NewMessage' %} ">New message</button></a>
    <a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo" href=" {% url 'users:Profile' user.id %} ">Return to Profile</button></a>
</div>

{% endblock messages %}

ProyectoFinal/Users/templates/Users/new_msg.html
{% extends 'Users/profile.html' %}

{% block messages %}


<div class="w3-container w3-card-4">
    <h3>{{title}}</h3>
</div>

<!-- Form nuevo mensaje -->
<div class="w3-container w3-padding-16">
    <form action="{% url 'blogapp:NewMessage' %}" method="POST">{% csrf_token %}
        <table class="w3-table-all w3-card-4">
            {{form.as_table}}
        </table>
        
        <!-- Botones -->
        <div class="w3-bar w3-padding-32">
            <input button type="submit" class="w3-bar-item  w3-right w3-button w3-white w3-border w3-border-indigo w3-round-large" value="Send">
            <a button type="button" class="w3-button w3-white w3-border w3-border-indigo w3-round-large" href=" {% url 'blogapp:Messages' %} ">Return to Inbox</button></a>
        </div>
    </form>
</div>

{% endblock messages %}

ProyectoFinal/Users/templates/Users/profile.html
{% extends 'BlogApp/template.html' %}

{% load static %}

{% block content %}


<div class="w3-container w3-card-4 w3-center w3-padding-32">
    <h5><b>{{user.username}}</b></h5>
</div>

{% block messages %}

    {% if avatar %}
    <div class="w3-card-4 w3-center w3-white w3-display-container">
        <img class="w3-circle" height="400px" src="{{avatar}}" alt="avatar">
        {% if user.is_superuser %}   <!-- solo el Admin puede ver la opción de cambiar foto de perfil -->
            <div class="w3-display-bottommiddle w3-large w3-black"><a class="w3-button w3-black w3-border" title="Change profile picture" href="{% url 'users:editAvatar' %}"><i class="fa fa-file-image-o"></i></a></div>
        {% endif %}
    </div>
    {% else %}
    <div class="w3-card-4 w3-center w3-white w3-display-container">
        <img src="{% static 'BlogApp/Profile-Pic-Icon-empty.png' %}" class="w3-circle" height="400px" alt="avatar">
        {% if user.is_superuser %}   <!-- solo el Admin puede ver la opción de cambiar foto de perfil -->
            <div class="w3-display-bottommiddle w3-large w3-black"><a class="w3-button w3-black w3-border" title="Add a profile picture" href="{% url 'users:editAvatar' %}"><i class="fa fa-file-image-o"></i></a></div>
        {% endif %}
    </div>
    {% endif %}

<!-- datos del usuario -->
<div class="w3-card-4 w3-center">
    <h4>
        <ul>
            <ol>Nombre Usuario: {{user.username}}</ol>
            <ol>Nombre: {{user.first_name}}</ol>
            <ol>Apellido: {{user.last_name}}</ol>
            <ol>Email: {{user.email}}</ol>
            <ol>Last access: {{user.last_login}}</ol>
            <ol>Joined: {{user.date_joined}}</ol>
    </ul>
    </h4>
</div>

<!-- Botones -->
<a button type="button" class="w3-button w3-block w3-round-large w3-indigo" href=" {% url 'blogapp:Messages' %} "><i class="fa fa-envelope-o"></i> Inbox</button></a>

<div class="w3-bar w3-padding-32 w3-center">
    <a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo w3-right" href=" {% url 'users:editProfile' %} ">Actualizar Perfil</button></a>
    <a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo w3-left" href=" {% url 'blogapp:Home' %} ">Return to Home</button></a>

</div>

{% endblock messages %}

{% endblock %}

ProyectoFinal/Users/templates/Users/register.html
{% extends 'BlogApp/template.html' %}

{% block content %}


<div class="w3-panel w3-pale-red w3-display-container">
    <span onclick="this.parentElement.style.display='none'"
    class="w3-button w3-large w3-display-topright">&times;</span>
    <h3>Bienvenido! Para acceder al blog es necesario crear una cuenta. Siga las siguientes instrucciones:</h3>
    <ul>El username no puede contener mas de 150 caracteres, solo letras numeros y "@/./+/-/_".<br>
        El password no puede ser similar a los detalles registrados.<br>
        El password debe contener al menos 8 caracteres, 1 letra y 1 numero.</ul>    
</div>


<!-- Formulario -->
<form action="{% url 'users:Register' %}" method="post">{% csrf_token %}

    <table class="w3-table w3-topbar w3-bottombar w3-border-dark-grey w3-round">
        {{ form.as_table }}
        </table>
        
        <!-- Botones -->
        <div class="w3-bar w3-padding-32">
        <input button type="submit" class="w3-button w3-round-large w3-button w3-large w3-indigo" value="Registrar">
        <a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo" href=" {% url 'blogapp:Home' %} ">Inicio</button></a>
        </div>
    </form>
</form>

{% endblock %}