ProyectoFinal/BlogApp/urls.py
from django.urls import path
from .views import *
from Users.views import messages, new_message

app_name = 'blogapp'

urlpatterns = [
    path("", home, name='Home'),
    path('posts/', posts, name='Posts'),
    path('posts/list/', PostList.as_view(), name='PostsList'),
    path('post/<pk>', PostDetail.as_view(), name='PostDetail'),
    path('post/delete/<pk>', PostDelete.as_view(), name='PostDelete'),
    path('post_form/', postForm, name='PostForm'),
    path('post/edit/<post_id>/', editPost, name='EditPost'),
    
    path('search_post/', searchPost, name="SearchPost"),
    path('search_result/', searchResult, name="SearchResult"),

    path('about/', about, name="About"),

    path('inbox/', messages, name='Messages'),
    path('inbox/new_msg/', new_message, name='NewMessage'),
]

ProyectoFinal/Users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', login_request, name='Login'),
    path('register/', register, name='Register'),
    path('logout/', LogoutView.as_view(template_name='Users/logout.html'), name='Logout'),   #el logout tiene su propia View y dentro del parentesis configuramos la vista
    path('editProfile/', editProfile, name='editProfile'),
    path('profile/<user_id>', profile, name='Profile'),
    path('edit/avatar/', editAvatar, name='editAvatar'),
]

ProyectoFinal/projectBlog/urls.py
from django.contrib import admin
from django.urls import path, include
#Para las imagenes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BlogApp.urls')),
    path('Users/', include('Users.urls')),
]

#Para las imagenes
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/BlogApp/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Crear el modelo Post en nuesta BD para guardar los posts

class Post(models.Model):
    """class representing post"""
    maquinaria = models.CharField(max_length=200)
    marca = models.CharField(max_length=200)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='images', null=True, blank = True)
    detalle = RichTextField()

    class Meta:
        ordering = ['-fecha']

def __str__(self):
    return self.maquinaria

ProyectoFinal/BlogApp/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget   #widget which adds rich text editor without image uploader
from .models import *


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        fields = ("maquinaria", "marca", "usuario", "imagen", "detalle")

ProyectoFinal/BlogApp/views.py
from django.shortcuts import render, redirect
#para el CRUD:
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
#importamos forms.py:
from BlogApp.forms import *
#mixin y decoradores:
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import *


# Create your views here.

def home(request):
    posts = Post.objects.all().order_by('-fecha') [0:3]
    return render (request, 'BlogApp/home.html', {'posts': posts})

#---------creacion del CRUD mediante CBV (Clases basadas en vistas)------------------

class PostList(ListView):
    model = Post
    template_name = 'BlogApp/posts.html'

class PostDetail(DetailView):
    model = Post
    template_name = 'BlogApp/post_detail.html'

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/posts/'


#-------------------view Posts--------------------------------------------------
def posts(request):

    posts = Post.objects.all().order_by('-fecha')
    return render(request, "BlogApp/posts.html", {"posts":posts})

#------------nueva funcion para mi form que permite agregar Posts-------------------

@login_required
def postForm(request):

    if request.method == 'POST':
        myForm = PostForm(request.POST, request.FILES)
        print(myForm)

        if myForm.is_valid():
            info = myForm.cleaned_data
            post = Post(maquinaria=info['maquinaria'], marca=info['marca'], usuario=info['usuario'],imagen=info['imagen'], detalle=info['detalle'])
            post.save()
            return redirect('blogapp:Posts')
    else:
        myForm = PostForm()
    return render(request, 'BlogApp/post_form.html', {"myForm":myForm})

#---------------------------Edit post---------------------------------------

@login_required
def editPost(request, post_id):

    #recibe el id del post que vamos a modificar
    post = Post.objects.get(id=post_id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES ,instance=post)
        if form.is_valid():
            form.save()
            return redirect('blogapp:Posts')
    else:
        form = PostForm(instance=post)
    return render(request, 'BlogApp/edit_post.html',{'form':form, 'maquinaria':post.maquinaria})


#-------------------searchPosts-------------------------------------------

def searchPost(request):

    return render(request, 'BlogApp/searchPost.html')

def searchResult(request):


    if request.GET["maquinaria"]:
        maquinaria = request.GET["maquinaria"]
        post = Post.objects.filter(title__icontains=maquinaria).order_by("-fecha")
        return render(request, 'BlogApp/searchPost.html', {"post":post})
    else:
        response="No ingreso ninguna informacion."
    return render(request, 'BlogApp/posts.html', {"response":response})


#-------------------------about us-------------------------------------------

def about(request):

    return render(request, "BlogApp/about.html")

ProyectoFinal/BlogApp/templates/BlogApp/about.html
{% extends 'BlogApp/template.html' %}

{% block content %}

<div class="w3-panel w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    <h1>Sobre Nosotros</h1>
</div>


<div class="w3-container w3-round-large w3-padding-16 w3-margin-top w3-margin-bottom">
    <div class="w3-card-4 w3-margin-top">
        <header class="w3-container">
            <h1>Sobre Nosotros:</h1>
        </header>
        <div class="w3-container">
            <h3>Iniciando en el mundo de la programación!</h3>
            <h4>Somos Nahuel y Miguel iniciando nuestra carrera en el área de programación.</h4>
            <h4>Este blog es parte del desafío final del curso de Python de CoderHouse, donde hemos visto el framework de aplicaciones web open-source Django.</h4>
            <h4>Ambos estamos interesados en seguir progresando con nuestros proyectos y realizar diseños que puedan ser de utilidad en pequeñas empresas que necesiten automatizar sus gestiones administrativas, hacer conocer sus productos mediante una página web.</h4>
        </div>
</div>

<div class="w3-container w3-round-large w3-padding-16 w3-margin-top w3-margin-bottom">
    <div class="w3-card-4 w3-margin-top">
        <div class="w3-container w3-padding-16 w3-margin-top">
            <h5>Para contactarse conmigo pueden buscarnos por Linkedin: 
            <a href = "link: https://www.linkedin.com/in/nahuelim">https://www.linkedin.com/in/nahuelim</a>
            <a href = "link: https://www.linkedin.com/in/miguelserrudo">https://www.linkedin.com/in/miguelserrudo</a></h5>
        </div>
    </div>
</div>





{% endblock %}

ProyectoFinal/BlogApp/templates/BlogApp/edit_post.html
{% extends 'BlogApp/posts.html' %}

{% block posts %}

<div class="w3-panel w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    <h1>You are about to edit Post: {{title}}</h1>
</div>


<!-- Form edit posts -->
<form action="{{post.id}}" method="POST">{% csrf_token %}

    <table class="w3-table w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    {{form.media}}
    {{form.as_table|safe}}
    </table>
    
    <!-- Botones -->
    <div class="w3-bar w3-padding-32">
        <input button type="submit" class="w3-button w3-round-large w3-button w3-large w3-indigo" value="Save changes">
        <a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo" href=" {% url 'blogapp:Posts' %} ">Return</button></a>
    </div>
</form>

{% endblock posts %}

ProyectoFinal/BlogApp/templates/BlogApp/home.html
{% extends 'BlogApp/template.html' %}

{% load static %}

{% block content %}

<div class="w3-container w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    <h1>Pagina de Inicio</h1>
    <h3 class="w3-opacity" style="text-shadow:1px 1px 0 #444"></h3>
</div>

{% if user.is_authenticated %}
    <div class="w3-container w3-light-grey w3-leftbar w3-rightbar w3-center">
        <h5 style="color:navy">Bienvenido, <b>{{user.username}}</b>.</h5>
    </div>   
{% endif %}

<!-- Contenido (imagen principal) -->
<div class="w3-panel">
    <div class="aligncenter w3-white">
        <img src="{% static 'BlogApp/home-banner.png' %}" class="w3-round" alt="banner">
        <style> -->
            .aligncenter {
            text-align: center;
            };
        </style>
    </div>
</div>


<!-- Posts display -->
{% if post %}
    <div class="w3-panel">
        <h1>Ultimos Posts</h1>
        {% for post in posts %}
            <div class="w3-card-4" style="width:70%">
                <header class="w3-container w3-light-grey"><h3>{{ post.maquinaria }}</h3></header>
                <div class="w3-container">
                    <p>{{ post.usuario }} | {{ post.fecha }}</p>
                    <hr>
                    {% if post.imagen %}
                        <img src="{{post.imagen.url}}" class="w3-left w3-round w3-margin-right" style="width:200px" alt="title">
                    {% endif %} 
                    <p>{{ post.marca }}</p><br>
                </div>
                <a button class="w3-button w3-block w3-dark-grey" href="{% url 'blogapp:PostDetail' post.id %}">Mas..</a>
            </div>
        {% endfor %}
    </div>
    <div class="w3-panel w3-white">
        <a href="{% url 'blogapp:Posts' %}" class="w3-button w3-dark-grey"><i class="fa fa-list-ul w3-margin-right"></i>Ver Todos</a>
    </div>
{% endif %}


{% endblock %}

ProyectoFinal/BlogApp/templates/BlogApp/post_confirm_delete.html
{% extends 'BlogApp/template.html' %}

{% load static %}

{% block content %}

<div class="w3-container w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-indigo w3-round">
    <h1>Delete Post</h1>
</div>

<form method="POST">{% csrf_token %}
    
    Are you sure you want to delete the following post: <b>"{{ object }}"?</b><br>
    This action can't be undone!
    
    <div class="w3-bar w3-padding-32 w3-center">
        <input button type="submit" class="w3-button w3-round-large w3-button w3-large w3-red" value="Delete">
        <a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo" href=" {% url 'blogapp:Posts' %} ">Return</button></a>
    </div>
</form>

{% endblock %}

ProyectoFinal/BlogApp/templates/BlogApp/post_detail.html
{% extends 'BlogApp/posts.html' %}

{% block content %}
{% block posts %}

<div class="w3-container w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    <h1>Ver los detalles del Post: {{post.title}}</h1>
</div>

<div class="w3-container w3-center w3-round">
    <h4>{{post.maquinaria}}</h4>
    <p class="w3-opacity">Dato de Post: {{post.fecha}}</p>
</div>

{% if post.imagen %}
        <div class="w3-center w3-display-container w3-card-4">
            <img src="{{post.imagen.url}}" alt="" class="w3-border w3-padding" height="500px" alt="title">
        </div>

{% else %}
        <div class="w3-center w3-display-container w3-card-4">
            <i class="fa fa-image w3-jumbo"></i>
            <p><b>{{post.usuario}}</b> aún no he agregado una imagen para esta publicación</p>
        </div>
{% endif %}

<div class="w3-container w3-center w3-round">
    <h4>{{post.marca}}</h4>
</div>

<div class="w3-container w3-card-4  w3-round">
    <p>{{post.detalle|safe}}</p>
</div>

<div class="w3-container">
    <p class="w3-opacity w3-right-align">Usuario: {{post.usuario}}</p>
</div>

<!-- Botones -->
<div class="w3-bar w3-padding-32">
<a button type="button" class="w3-button w3-round-large w3-large w3-indigo" href=" {% url 'blogapp:Posts' %} ">Retornar</button></a>

<!-- Solo autor del posts puede modificar/eliminar -->
{% if request.user == post.usuario %}
    <a href="{% url 'blogapp:EditPost' post.id %}" class="w3-button w3-round-large w3-large w3-indigo w3-right"><i class="fa fa-edit"></i> Editar Post</a>
    <a href="{% url 'blogapp:PostDelete' post.id %}" class="w3-button w3-round-large w3-large w3-indigo w3-right"><i class="fa fa-edit"></i> Borrar Post</a>
{% endif %}
</div>

{% endblock posts %}
{% endblock %}

ProyectoFinal/BlogApp/templates/BlogApp/post_form.html
{% extends 'BlogApp/posts.html' %}

{% block posts %}

<div class="w3-panel w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    <h1>Nuevo Post</h1>
</div>

<!-- Form nuevo post -->

<form enctype="multipart/form-data" action="{% url 'blogapp:PostForm' %}" method="POST">{% csrf_token %}

    <table class="w3-table w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    {{ myForm.media }}
    {{ myForm.as_table|safe }}
    </table>
    
    <!-- Botones -->
    <div class="w3-bar w3-padding-32">
        <input button type="submit" class="w3-button w3-round-large w3-button w3-large w3-indigo" value="Enviar">
        <a button type="button" class="w3-button w3-round-large w3-button w3-large w3-indigo" href=" {% url 'blogapp:Posts' %} ">Retornar</button></a>
    </div>
</form>

{% endblock posts %}

ProyectoFinal/BlogApp/templates/BlogApp/posts.html
{% extends 'BlogApp/template.html' %}

{% block content %}
{% block posts %}

<!-- Title and subtitle -->
<div class="w3-panel w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-dark-grey w3-round">
    <h1>Posts</h1>
    <h3 class="w3-opacity" style="text-shadow:1px 1px 0 #444">Ver los detalles del Post:</h3>
</div>

<!-- Buscar Post -->
<div class="w3-panel">
    <h3>Puede Buscar un Titulo:</h3>

    <form action="{% url 'blogapp:SearchResult' %}" method="GET">
        <input type="text" name="maquinaria" id="maquinaria">
        <input button type="submit" class="w3-button w3-round-large w3-button w3-indigo" value="Buscar">
    </form>
</div>

{% if posts %}
    
    <!-- Tabla -->
    
    <div class="w3-container">
        <table class="w3-table-all w3-hoverable">
            <thead>
                <tr class="w3-dark-grey w3-wide">
                    <th>Maquinaria</th>
                    <th>Marca</th>
                    <th>Usuario</th>
                    <th>Fecha de Publicacion</th>
                    <th>detalle</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <th>{{post.maquinaria}}</th>
                        <td>{{post.marca}}</td>
                        <td>{{post.usuario}}</td>
                        <td>{{post.fecha}}</td>
                        <td>{{post.detalle|slice:':70'|safe}} <a class="w3-text-blue" href="{% url 'blogapp:PostDetail' post.id %}">... [Leer Mas]</a></td>
                        <td> 
                            {% if request.user == post.usuario %}
                            <!-- Botones de tabla -->
                            <a href="{% url 'blogapp:PostDelete' post.id %}" class="w3-button w3-round w3-indigo w3-small"><i class="fa fa-trash"></i> Borrar Post</a>
                            <a href="{% url 'blogapp:EditPost' post.id %}" class="w3-button w3-round w3-indigo w3-small"><i class="fa fa-edit"></i> Editar Post</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>    


{% endif %}

<!-- Botones -->
<div class="w3-bar w3-padding-32">
    <a button class="w3-button w3-round-large w3-button w3-large w3-indigo" href="{% url 'blogapp:PostForm' %}"><i class="fa fa-edit"></i> Crear Nuevo Post</a>
    
</div>

{% endblock posts %}
{% endblock content %}

ProyectoFinal/BlogApp/templates/BlogApp/searchPost.html
{% extends 'BlogApp/posts.html' %}

{% block posts %}

<div class="w3-container w3-padding-16 w3-center w3-topbar w3-bottombar w3-border-indigo w3-round">
    <h1>Search Result</h1>
</div>


{% if post %}

<h3>Titles that may interest you from your search:</h3>

<ol>
    {% for title in post %}
        <li><a href="{% url 'blogapp:Posts' %}">{{title.maquinaria}} - {{title.fecha}}</a></li>
    {% endfor %}
</ol>

{% else %}
<div class="w3-panel w3-blue-gray">
    <h5>We don't have any post for that title. You can be the first in writing about it!</h5>
</div>
<div class="w3-bar w3-padding-32">
    <a button class="w3-button w3-round-large w3-button w3-large w3-indigo" href="{% url 'blogapp:PostForm' %}"><i class="fa fa-edit"></i> Create New Post</a>
</div>

{% endif %}

<!-- Botones -->
<div class="w3-bar w3-padding-32">
<a button type="button" class="w3-button w3-round-large w3-large w3-indigo" href=" {% url 'blogapp:Posts' %} ">Return</button></a>
</div>

{% endblock posts %}

ProyectoFinal/BlogApp/templates/BlogApp/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    
{% load static %}    
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>{{title}}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'BlogApp/home-icon.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <!-- Navbar -->
    {% include 'BlogApp/components/navbar.html' %}

    <!-- Title and subtitle -->
    <div class="w3-container w3-round w3-light-gray">
        <div class="w3-panel w3-dark-grey w3-padding-16 w3-border w3-round-large">
            <h1>Todo sobre Tractores<br>
            <small class="w3-opacity">Bienvenido al blog de todo sobre tractores</small></h1> 
        </div>
    </div>

    <!-- Content que va a cambiar -->
    <div class="w3-container">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Footer -->
    {% include 'BlogApp/components/footer.html' %}
</body>
</html>