ProyectoFinal/BlogApp/urls.py
from django.urls import path
from .views import *
from Users.views import messages, new_message

app_name = 'blogapp'

urlpatterns = [
    path("", home, name='Home'),
    path('posts/', posts, name='Posts'),
    path('posts/list/', PostList.as_view(), name='PostsList'),
    path('post/<pk>', PostDetail.as_view(), name='PostDetail'),
    path('post/delete/<pk>', PostDelete.as_view(), name='PostDelete'),
    path('post_form/', postForm, name='PostForm'),
    path('post/edit/<post_id>/', editPost, name='EditPost'),
    
    path('search_post/', searchPost, name="SearchPost"),
    path('search_result/', searchResult, name="SearchResult"),

    path('about/', about, name="About"),

    path('inbox/', messages, name='Messages'),
    path('inbox/new_msg/', new_message, name='NewMessage'),
]

ProyectoFinal/Users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', login_request, name='Login'),
    path('register/', register, name='Register'),
    path('logout/', LogoutView.as_view(template_name='Users/logout.html'), name='Logout'),   #el logout tiene su propia View y dentro del parentesis configuramos la vista
    path('editProfile/', editProfile, name='editProfile'),
    path('profile/<user_id>', profile, name='Profile'),
    path('edit/avatar/', editAvatar, name='editAvatar'),
]

ProyectoFinal/projectBlog/urls.py
from django.contrib import admin
from django.urls import path, include
#Para las imagenes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BlogApp.urls')),
    path('Users/', include('Users.urls')),
]

#Para las imagenes
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/BlogApp/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Crear el modelo Post en nuesta BD para guardar los posts

class Post(models.Model):
    """class representing post"""
    maquinaria = models.CharField(max_length=200)
    marca = models.CharField(max_length=200)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='images', null=True, blank = True)
    detalle = RichTextField()

    class Meta:
        ordering = ['-fecha']

def __str__(self):
    return self.maquinaria

ProyectoFinal/BlogApp/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget   #widget which adds rich text editor without image uploader
from .models import *


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        fields = ("maquinaria", "marca", "usuario", "imagen", "detalle")

ProyectoFinal/BlogApp/views.py
from django.shortcuts import render, redirect
#para el CRUD:
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
#importamos forms.py:
from BlogApp.forms import *
#mixin y decoradores:
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import *


# Create your views here.

def home(request):
    posts = Post.objects.all().order_by('-fecha') [0:3]
    return render (request, 'BlogApp/home.html', {'posts': posts})

#---------creacion del CRUD mediante CBV (Clases basadas en vistas)------------------

class PostList(ListView):
    model = Post
    template_name = 'BlogApp/posts.html'

class PostDetail(DetailView):
    model = Post
    template_name = 'BlogApp/post_detail.html'

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/posts/'


#-------------------view Posts--------------------------------------------------
def posts(request):

    posts = Post.objects.all().order_by('-fecha')
    return render(request, "BlogApp/posts.html", {"posts":posts})

#------------nueva funcion para mi form que permite agregar Posts-------------------

@login_required
def postForm(request):

    if request.method == 'POST':
        myForm = PostForm(request.POST, request.FILES)
        print(myForm)

        if myForm.is_valid():
            info = myForm.cleaned_data
            post = Post(maquinaria=info['maquinaria'], marca=info['marca'], usuario=info['usuario'],imagen=info['imagen'], detalle=info['detalle'])
            post.save()
            return redirect('blogapp:Posts')
    else:
        myForm = PostForm()
    return render(request, 'BlogApp/post_form.html', {"myForm":myForm})

#---------------------------Edit post---------------------------------------

@login_required
def editPost(request, post_id):

    #recibe el id del post que vamos a modificar
    post = Post.objects.get(id=post_id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES ,instance=post)
        if form.is_valid():
            form.save()
            return redirect('blogapp:Posts')
    else:
        form = PostForm(instance=post)
    return render(request, 'BlogApp/edit_post.html',{'form':form, 'maquinaria':post.maquinaria})


#-------------------searchPosts-------------------------------------------

def searchPost(request):

    return render(request, 'BlogApp/searchPost.html')

def searchResult(request):


    if request.GET["maquinaria"]:
        maquinaria = request.GET["maquinaria"]
        post = Post.objects.filter(title__icontains=maquinaria).order_by("-fecha")
        return render(request, 'BlogApp/searchPost.html', {"post":post})
    else:
        response="No ingreso ninguna informacion."
    return render(request, 'BlogApp/posts.html', {"response":response})


#-------------------------about us-------------------------------------------

def about(request):

    return render(request, "BlogApp/about.html")

ProyectoFinal/BlogApp/templates/BlogApp/components/footer.html
<!-- Footer -->

<footer class="w3-center w3-black w3-padding-64 w3-opacity w3-hover-opacity-off">
    <a href="{% url 'blogapp:Home' %}" class="w3-button w3-light-grey"><i class="fa fa-arrow-up w3-margin-right"></i>Inicio</a>
    <div class="w3-xlarge w3-section">
      <i class="fa fa-facebook-official w3-hover-opacity"></i>
      <i class="fa fa-instagram w3-hover-opacity"></i>
      <i class="fa fa-snapchat w3-hover-opacity"></i>
      <i class="fa fa-pinterest-p w3-hover-opacity"></i>
      <i class="fa fa-twitter w3-hover-opacity"></i>
      <i class="fa fa-linkedin w3-hover-opacity"></i>
    </div>
    <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-text-green">w3.css</a></p>
</footer>

ProyectoFinal/BlogApp/templates/BlogApp/components/navbar.html
<!-- Navbar icons -->
<div class="w3-bar w3-black w3-border w3-padding-large">

    <a href="{% url 'blogapp:Home' %}" class="w3-bar-item w3-button"><i class= "fa fa-home"></i> Home</a>
    <a href="{% url 'blogapp:Posts' %}" class="w3-bar-item w3-button"><i class="fa fa-list-ul"></i> Posts</a>
    <a href="{% url 'blogapp:About' %}" class="w3-bar-item w3-button"><i class="fa fa-info-circle"></i> Sobre Nosotros</a>

    <!-- Dropdown list -->
    {% if user.is_authenticated %}
        <div class="w3-dropdown-hover w3-right">

            <button class="w3-button w3-small">
                <img class="w3-circle" width="20px" src="{{avatar}}"></img>
                {{user.username}}
            </button>

            <div class="w3-dropdown-content w3-bar-block w3-card-4">
                <a href="{% url 'users:Profile' user.id %}" class="w3-bar-item w3-button"><i class="fa fa-user-o"></i> Perfil</a>
                <a href="{% url 'blogapp:Messages' %}" class="w3-bar-item w3-button"><i class="fa fa-envelope-o"></i> Mensajes</a>
                <a href="{% url 'users:Logout' %}" class="w3-bar-item w3-button"><i class="fa fa-window-close-o"></i> Cerrar</a>
            </div>
        </div>
    {% else %}
        <!-- Only show if user is not authenticated -->
        <a button class="w3-bar-item w3-button w3-round-large w3-button w3-blue w3-right w3-margin-left" href="{% url 'users:Register' %}"><b>Registro</b></a>
        <a button class="w3-bar-item w3-button w3-round-large w3-button w3-blue w3-right" href="{% url 'users:Login' %}"><b>Iniciar Sesión</b></a>
    {% endif %}
</div>